In [1]:
import tensorflow as tf

In [5]:
# 扩充0
tf.zeros([1,3,3])

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [6]:
# 扩充1
tf.ones([1,3,3])

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [7]:
# 扩充指定的值
tf.fill([1,3,3],99)

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]]])>

In [10]:
# 随机数，从标准正太分布中生成随机
tf.random.normal([1,3,3],mean=1,stddev=1)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 1.6797717 ,  2.984737  ,  1.402016  ],
        [ 1.6980629 ,  1.8256819 ,  0.08721715],
        [ 0.43552577,  1.4258475 , -0.37625754]]], dtype=float32)>

In [ ]:
# 生成截断式的正态分布的随机数
tf.random.truncated_normal([1,3,3],mean=1,stddev=1)